### ISSUE TITLE
LTI Settings > Appearance > Display only book content in LMS

### ISSUE THREAD

**Issue by dac514** [pressbooks/pressbooks-lti-provider#1]
### Prerequisites

* [X] Can you reproduce the behavior you wish to address with [all plugins except Pressbooks and this plugin deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [X] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/), the latest version of [this plugin](http://github.com/pressbooks/pressbooks-lti-provider/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks-lti-provider) to see if your bug or enhancement is already listed?

### Description

What CSS/JS/Wizardy do we inject when `hide_navigation` setting is set to `1` Currently this setting does nothing. I need some tips from @greatislander  for this one.

> [Source](https://github.com/pressbooks/pressbooks-lti-provider/blob/d0d1c8242328fb311fb6d2ce8c683ce07d5df5a6/inc/class-admin.php#L276)
> [Related issue](https://github.com/pressbooks/pressbooks-book/issues/36)

**Comment by greatislander** [comment]
@connerbw Styles are handled via https://github.com/pressbooks/pressbooks-book/pull/196. To make them work the body needs a class of `.no-navigation`.

PHP implementation:

```
add_filter( 'body_class', function( $classes ) {
  $classes[] = 'no-navigation';
  return $classes;
}
```

JS implementation:

```
document.addEventListener( 'DOMContentLoaded', function () {
  document.body.classList.add( 'no-navigation' );
} );
```

Not sure which is easiest? Let's discuss.
