### ISSUE TITLE
Pressbooks LTI provider exports CC 1.1 properly but labels the file as XHTML

### ISSUE THREAD

**Issue by beckej13820** [pressbooks/pressbooks-lti-provider#10]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all plugins except Pressbooks and this plugin deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/), the latest version of [this plugin](http://github.com/pressbooks/pressbooks-lti-provider/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks-lti-provider) to see if your bug or enhancement is already listed?

### Description

When exporting LTI common cartridge 1.1, export file gets labeled as XHTML. 

### Steps to Reproduce

1. Set export CC 1.1 for Moodle
2. Export Thin CC 1.1
3. See that cartridge is labeled XHTML, but when it is downloaded it is still an .imscc and does import into Moodle properly.

**Expected behavior:** 

I'd export the CC file to be labeled as the file type and the version

**Actual behavior:** 

The file is labeled XHTML.

#### Book Info

Book ID: 15
Book URL: http://oer.ed-beck.com/forallx/
Book Privacy: Public

#### Browser

Platform: OS X
Browser Name: Chrome
Browser Version: 66.0.3359.139
User Agent String: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36

#### WordPress Configuration

Network URL: http://oer.ed-beck.com/
Network Type: Subdirectory
Version: 4.9.6
Language: en_US
WP_ENV: production
WP_DEBUG: Disabled
Memory Limit: 5000M

#### Pressbooks Configuration

Version: 5.3.0
Book Theme: Jacobs
Book Theme Version: 1.0.0
Root Theme: Aldine
Root Theme Version: 1.3.0

#### Pressbooks Dependencies

Epubcheck: Installed
Kindlegen: Installed
xmllint: Installed
PrinceXML: Installed
Saxon-HE: Installed

#### Must-Use Plugins

hm-autoloader.php: n/a

#### Network Active Plugins

GitHub Updater: 7.6.2
Openstax Import for Pressbooks: 1.2.0
Pressbooks: 5.3.0
Pressbooks LTI Provider: 0.4.0
Pressbooks Stats: 1.4.1

#### Book Active Plugins

WP QuickLaTeX: 3.8.4
Wp Show Site ID: 1.0.0

#### Inactive Plugins

Akismet Anti-Spam: 4.0.3
Candela Links: 0.1
Candela LTI: 0.1
Candela Thin Exports: 0.1
CC Export for Pressbooks: 0.2.1
Docraptor for Pressbooks: 2.2.1
H5P: 1.10.2
Hello Dolly: 1.6
Hypothesis: 0.5.0
LTI: 0.1
mPDF for Pressbooks: 3.1.2

#### Server Configuration

PHP Version: 7.0.30-0ubuntu0.16.04.1
MySQL Version: 5.7.22
Webserver Info: Apache/2.4.18 (Ubuntu)

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 5000M
Upload Max Size: 2000M
Post Max Size: 2000M
Upload Max Filesize: 2000M
Time Limit: 30
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: N/A

#### PHP Extensions

OPcache: Zend
XDebug: Disabled
cURL: Supported
cURL Version: 7.47.0
imagick: Installed
xsl: Installed

**Comment by dac514** [comment]
Thanks for testing @beckej13820. Appreciated.

This is fixed in the dev branch here: https://github.com/pressbooks/pressbooks-lti-provider/commit/d2ab999eaab56296b07c6dd678ded81cf02c9522
