### ISSUE TITLE
Switch to GitHub Actions

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks-lti-provider#127]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all plugins except Pressbooks and this plugin deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/), the latest version of [this plugin](http://github.com/pressbooks/pressbooks-lti-provider/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks-cas-sso) to see if your bug or enhancement is already listed?

### Description

This repository is still using Travis, and should be switched to GitHub Actions. Noticed while working on #126.

### Steps to Reproduce

Not applicable.

**Comment by SteelWagstaff** [comment]
Closing as a 'won't fix,' since we'll be archiving the plugin shortly.
