### ISSUE TITLE
Investigate lis_person_sourcedid support

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks-lti-provider#28]
### Description

Investigate creating and matching users with the `lis_person_sourcedid` property as the email address in LMSes [which support it](https://www.imsglobal.org/toolcompare.html).

**Comment by anf107** [comment]
IMS has some good information out there at [http://www.imsglobal.org/best-practices-managing-ids-lti](http://www.imsglobal.org/best-practices-managing-ids-lti) about how to handle identity.  The `lis_person_sourcedid` value is what they want to use, but I can't find any new information from other platforms that conflict with the "toolscompare" link above.

**Comment by greatislander** [comment]
@anf107 To be clear, we use the `user_id` from the LMS for matching. We also need an email address to create a Pressbooks (WordPress) account and we use it as a fallback matching method if the `user_id` is not present for some reason. I think the biggest challenge is ensuring a consistent experience for users of different LMSes, some of which do not implement `lis_person_sourcedid`.

**Comment by dac514** [comment]
We have customers that expect that LTI and SSO be the same user. In all cases, we are not matching users with email. We are creating them if they don't exist yet, and in order to create a Pressbooks user (aka WordPress), we need an email.

**Comment by dac514** [comment]
The tricky part is how to ensure that both SSO and LTI match the same user? Because SSO and LTI don't share the same userid, then the most reliable mechanism, so far, has been email. I think this is where the confusion is?
