### ISSUE TITLE
Who can show me a successefully-running Pressbooks & Moodle configuration page screenshot?

### ISSUE THREAD

**Issue by fishfree** [pressbooks/pressbooks-lti-provider#55]
I need enable Content Selection feature, preferrably LTI 1.3.
I tried almost every possible configuration matching of the both sides.  In Moodle side, it still shows: An error occurred when launching the external tool:Sorry, there was an error connecting you to the application.

My Pressbooks&Pressbooks LTI provider and Moodle are both the latest stable version.

**Comment by dac514** [comment]
Post questions like this one in the community forum; https://pressbooks.community/
