### ISSUE TITLE
Keyboard navigation still works with navigation elements suppressed.

### ISSUE THREAD

**Issue by beckej13820** [pressbooks/pressbooks-lti-provider#7]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all plugins except Pressbooks and this plugin deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/), the latest version of [this plugin](http://github.com/pressbooks/pressbooks-lti-provider/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks-lti-provider) to see if your bug or enhancement is already listed?

### Description

When testing out the the new LTI in development, I turned Pressbooks navigation off to only show content. While there was no next chapter or previous chapter as expected, when I used the left and right arrow keys on the keyboard, I was still able to move from chapter to chapter.

This was tested with Moodle 3.4.
### Steps to Reproduce

1. Set up LTI and import a book
2. In the integrations menu select "Display only book content in LMS"
3. On a chapter, test left and right arrows to test for navigation

I'd expect navigation to be unavailable if the visual indicators are unavailable.

**Actual behavior:** key navigation still worked.

#### Root Blog Info

Root Blog ID: 1
Root Blog URL: http://oer.ed-beck.com/

#### Browser

Platform: OS X
Browser Name: Chrome
Browser Version: 66.0.3359.139
User Agent String: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36

#### WordPress Configuration

Network URL: http://oer.ed-beck.com/
Network Type: Subdirectory
Version: 4.9.6
Language: en_US
WP_ENV: production
WP_DEBUG: Enabled
Memory Limit: 5000M

#### Pressbooks Configuration

Version: 5.3.0
Root Theme: Aldine
Root Theme Version: 1.3.0

#### Pressbooks Dependencies

Epubcheck: Installed
Kindlegen: Installed
xmllint: Installed
PrinceXML: Installed
Saxon-HE: Installed

#### Must-Use Plugins

hm-autoloader.php: n/a

#### Network Active Plugins

GitHub Updater: 7.6.2
Openstax Import for Pressbooks: 1.2.0
Pressbooks: 5.3.0
Pressbooks LTI Provider: 0.3.0
Pressbooks Stats: 1.4.1

#### Root Blog Active Plugins

Candela LTI: 0.1
WP QuickLaTeX: 3.8.4

#### Inactive Plugins

Akismet Anti-Spam: 4.0.3
Candela Links: 0.1
Candela Thin Exports: 0.1
CC Export for Pressbooks: 0.2.1
Docraptor for Pressbooks: 2.2.1
H5P: 1.10.1
Hello Dolly: 1.6
Hypothesis: 0.5.0
LTI: 0.1
mPDF for Pressbooks: 3.1.1
Wp Show Site ID: 1.0.0

#### Server Configuration

PHP Version: 7.0.30-0ubuntu0.16.04.1
MySQL Version: 5.7.22
Webserver Info: Apache/2.4.18 (Ubuntu)

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 5000M
Upload Max Size: 2000M
Post Max Size: 2000M
Upload Max Filesize: 2000M
Time Limit: 30
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: On (1)

#### PHP Extensions

OPcache: Zend
XDebug: Disabled
cURL: Supported
cURL Version: 7.47.0
imagick: Installed
xsl: Installed

**Comment by dac514** [comment]
Related: https://github.com/pressbooks/pressbooks-book/issues/207

**Comment by greatislander** [comment]
Closed in favour of https://github.com/pressbooks/pressbooks-book/issues/219.
