### ISSUE TITLE
Automatically create books via LTI link

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks-lti-provider#81]
Open source Pressbooks users at a university in Switzerland have been using an alternative WordPress LTI provider plugin that is no longer maintained: https://github.com/celtic-project/wordpress-lti. They would like to migrate to our LTI provider plugin, but have become reliant on a feature that is present in the other plugin but not in ours, namely the ability to automatically create a new book via LTI link: https://github.com/celtic-project/wordpress-lti/blob/5cb985b06f149cacdf64ab2bcfa3d69c58e139c2/lti/includes/doConnect.php#L124-L135. 

Recording of current functionality from plugin they're using with Moodle: https://www.youtube.com/watch?v=TpUbcXqCxI8

They would like to be able to create a new book in a Moodle course via LTI with our plugin. The book title should be '[Moodle Course Name]: [Moodle Activity Name]' and the book's URL should be [moodleactivityname]. 

They would also like to map previously created users upon launch of our LTI provider plugin. They are currently only storing a username: https://github.com/celtic-project/wordpress-lti/blob/5cb985b06f149cacdf64ab2bcfa3d69c58e139c2/lti/includes/doConnect.php#L88-L99 which is supposed to be the unique_id-consumer key. See https://github.com/celtic-project/wordpress-lti/blob/5cb985b06f149cacdf64ab2bcfa3d69c58e139c2/lti/includes/doConnect.php#L62-L70

Here is our current user matching functionality: https://github.com/pressbooks/pressbooks-lti-provider/blob/86ab658463b27b20441c2c2a7b236a8bccfcb958/inc/class-tool.php#L364-L372

**Comment by cagp-dev-mtl** [comment]
The new book LTI endpoint will be:

`https://pressbooks.test/format/lti/createbook`

URL actions are treated here:

`https://github.com/pressbooks/pressbooks-lti-provider-1p3/blob/1c5e1f08d2a4e847f1b8e135b648832f04357520/inc/namespace.php#L55`

As part of the work we will need to add a new condition that checks ` 'createbook' === $action `

**Steps**
- Validate LTI launch (Verify consumer key and shared secret)
- Create a book
- Log in user (Perform user match attempt)

**Requirements**
- Local installation of Moodle (Able to communicate with Pressbooks)
- Local installation of Pressbooks (Able to communicate with Moodle)
- LTI provider plugin enabled in Pressbooks
- Create an LTI 1.1 integration that points to your local Moodle application, set a key and shared secret.
- Enable a LTI 1.1 tool connector with the following URL: `https://[PRESSBOOKS DOMAIN]/format/lti/createbook`

The initial request handler commit is in branch:

`pb-81_lti_create_new_book`

**Comment by SteelWagstaff** [comment]
@bdolor The clients have provided the contents of the wp_users (https://drive.google.com/open?id=1bDMp8s1nbUKoEOC59CA2t5j8XA2seoFU) and wp_usermeta (https://drive.google.com/open?id=1bDMp8s1nbUKoEOC59CA2t5j8XA2seoFU) tables, stripped of identifying information. I believe that the users with five digit usernames (i.e. 48212 or 56642) and no email address are the ones created via their current LTI plugin. I don't know whether these user names correspond to the unique LTI ID provided by the LMS upon launch, but if they do, that would seem to be our best hope for a new user matching routine.

**Comment by SteelWagstaff** [comment]
Desired changes to user match routine: https://github.com/pressbooks/pressbooks-lti-provider/blob/86ab658463b27b20441c2c2a7b236a8bccfcb958/inc/class-tool.php#L364-L372
1. Add check to see if there is an existing user in our database whose username matches the user Id value received for that particular user (probably is an additional check run after line 369-370 in previous code).
2. If match is found, consider match condition met and add user meta to the matched user so that this value can be found/matched for all future logins

**Comment by SteelWagstaff** [comment]
@cagp-dev-mtl Two problems still persist in my testing:

1. When a student or user other than the person who created the book attempts to launch a 'private' book they sometimes see an 'access denied' message displayed when a book is private and the user does not have an account which authorizes them to view it:
![Screenshot from 2020-07-13 10-58-07](https://user-images.githubusercontent.com/13485451/87326007-cb009280-c4f7-11ea-8a14-062fa59997db.png). The expected behavior is that they should be given a user account and logged in to the book. See example at https://moodle.pressbooks.pub/mod/lti/view.php?id=69

2. Some createbook links result in the creation of multiple books. See the 'making another book' link in this test course: https://moodle.pressbooks.pub/mod/lti/view.php?id=59 for example. Each time a user launches this link a new book is created. Expected behavior is for the already created book to be displayed to the user.
